debug-messages: false
spawn-reason-allowed:
- NATURAL
- SPAWNER_EGG
mobs:
  SKELETON:
    mode: add
    mob-type:
      entity: HORSE
      variant: SKELETON_HORSE
      age: random
    custom-name: none
    hostile: true
    damage: 2
    tameable: true
    as-passanger: true
    spawn:
      amount: 2
      radius: 10
      chance: 20
  ZOMBIE:
    mode: add
    mob-type:
      entity: HORSE
      variant: UNDEAD_HORSE
      age: random
    custom-name: none
    hostile: true
    damage: 2
    tameable: true
    as-passanger: true
    spawn:
      amount: 2
      radius: 10
      chance: 20